/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufpso.binarytreearithmetic;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/** @author anderson */
public class GUI extends javax.swing.JFrame {

  /** Creates new form GUI */
  public GUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    _lblTitle = new javax.swing.JLabel();
    textFieldExpr = new javax.swing.JTextField();
    btnCalculate = new javax.swing.JButton();
    lblResult = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    _lblTitle.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
    _lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    _lblTitle.setText("Calculadora");

    btnCalculate.setText("Calcular");
    btnCalculate.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCalculateActionPerformed(evt);
          }
        });

    lblResult.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
    lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                _lblTitle,
                javax.swing.GroupLayout.Alignment.TRAILING,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(
                        textFieldExpr,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        182,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnCalculate)
                    .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(
                lblResult,
                javax.swing.GroupLayout.Alignment.TRAILING,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(_lblTitle)
                    .addGap(50, 50, 50)
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                textFieldExpr,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalculate))
                    .addGap(50, 50, 50)
                    .addComponent(lblResult)
                    .addContainerGap(109, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void btnCalculateActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_btnCalculateActionPerformed
    ArrayList<Token> tokens;
    try {
      tokens = BinaryTreeArithmetic.tokenize(textFieldExpr.getText());
    } catch (InvalidCharException ex) {
      JOptionPane.showMessageDialog(
          rootPane, ex, "Caracteres inválidos", JOptionPane.ERROR_MESSAGE);
      return;
    }

    BinaryTree tree = BinaryTreeArithmetic.toBinaryTree(tokens);
    String text =
        new DecimalFormat("#.##########").format(BinaryTreeArithmetic.executeBinaryTree(tree));
    lblResult.setText(text);
  } // GEN-LAST:event_btnCalculateActionPerformed

  /** @param args the command line arguments */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GUI.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          public void run() {
            new GUI().setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel _lblTitle;
  private javax.swing.JButton btnCalculate;
  private javax.swing.JLabel lblResult;
  private javax.swing.JTextField textFieldExpr;
  // End of variables declaration//GEN-END:variables
}
